---
title: WorkBright
baseURL: "http://workbright.com/"
languageCode: "en-us"

theme:          "wb-site-theme"
contentDir:     "content"
layoutDir:      "layouts"
metaDataFormat: "yaml"

params:
  description: Simplify the HR process with onboarding software solutions by WorkBright. Give employees a better new hire orientation with paperless onboarding.

menu:
  footer:
      - Name: "Solutions"
        Weight: 1
      - Name: "Customers"
        Weight: 2
      - Name: "Resources"
        Weight: 3
      - Name: "About"
        Weight: 4
      - Name: "Stay in Touch"
        Weight: 5

      - Name: "X Applicant Tracking System"
        Parent: "Solutions"
        Identifier: "about"
        URL: "#"
        Weight: 3
      - Name: "X Security"
        Parent: "Solutions"
        Identifier: "security"
        URL: "#"
        Weight: 4
      - Name: "X API & Integrations"
        Parent: "Solutions"
        Identifier: "api"
        URL: "#"
        Weight: 5

      - Name: "X Regulated"
        Parent: "Customers"
        Identifier: "regulated"
        URL: "#"
      - Name: "X Contingent"
        Parent: "Customers"
        Identifier: "contingent"
        URL: "#"
      - Name: "X Seasonal"
        Parent: "Customers"
        Identifier: "seasonal"
        URL: "#"
      - Name: "X High Turnover"
        Parent: "Customers"
        Identifier: "high_turnover"
        URL: "#"

      - Name: "Blog"
        Parent: "Resources"
        Identifier: "blog"
        URL: "/blog"
      - Name: "X Free Downloads"
        Parent: "Resources"
        Identifier: "free_downloads"
        URL: "#"
      - Name: "X Webinars"
        Parent: "Resources"
        Identifier: "webinars"
        URL: "#"
      - Name: "X Partner Program"
        Parent: "Resources"
        Identifier: "partner_programs"
        URL: "#"

      - Name: "X Leadership"
        Parent: "About"
        Identifier: "leadership"
        URL: "#"
      - Name: "X Core Values"
        Parent: "About"
        Identifier: "core_values"
        URL: "#"

      - Name: "X Contact"
        Parent: "Stay in Touch"
        Identifier: "contact"
        URL: "#"
        Weight: -10
      - Name: "Twitter"
        Parent: "Stay in Touch"
        URL: "https://twitter.com/workbrightHR"
        Pre: "<i class='icon-twitter'></i>"
        Weight: -4
      - Name: "Facebook"
        Parent: "Stay in Touch"
        Identifier: "facebook"
        URL: "https://www.facebook.com/workbright?ref=hl"
        Pre: "<i class='icon-facebook'></i>"
        Weight: -5
      - Name: "LinkedIn"
        Parent: "Stay in Touch"
        Identifier: "linkedin"
        URL: "https://www.linkedin.com/company/all4staff/"
        Pre: "<i class='icon-linkedin'></i>"
        Weight: -2

