---
title: WorkBright
baseURL: "http://www.workbright.com/"
languageCode: "en-us"

theme:          "wb-site-theme"
contentDir:     "content"
layoutDir:      "layouts"
metaDataFormat: "yaml"

params:
  description: Simplify the HR process with onboarding software solutions by WorkBright. New hire orientation made easy with paperless employee onboarding systems.
  address: 'WorkBright | PO Box 337 | Boulder, CO 80306'
  phone: '844-370-1783'

menu:
  footer:
      - Name: "Solutions"
        Weight: 1
      - Name: "Customers"
        Weight: 2
      - Name: "Resources"
        Weight: 3
      - Name: "Stay in Touch"
        Weight: 4

      - Name: "Case Studies"
        Parent: "Customers"
        Identifier: "case-studies"
        URL: "/case-studies"
      - Name: "Quotes"
        Parent: "Customers"
        Identifier: "quotes"
        URL: "/case-studies#quotes"

      - Name: "Blog"
        Parent: "Resources"
        Identifier: "blog"
        URL: "/blog"
      - Name: "Partner Program"
        Parent: "Resources"
        Identifier: "partner_program"
        URL: "https://workbright.growsumo.com/i"

      - Name: "Twitter"
        Parent: "Stay in Touch"
        URL: "https://twitter.com/workbrightHR"
        Pre: "<i class='icon-twitter'></i>"
        Weight: -4
      - Name: "Facebook"
        Parent: "Stay in Touch"
        Identifier: "facebook"
        URL: "https://www.facebook.com/workbright?ref=hl"
        Pre: "<i class='icon-facebook'></i>"
        Weight: -5
      - Name: "LinkedIn"
        Parent: "Stay in Touch"
        Identifier: "linkedin"
        URL: "https://www.linkedin.com/company/all4staff/"
        Pre: "<i class='icon-linkedin'></i>"
        Weight: -2

