backend:
  name: github
  repo: LastZactionHero/wb-website
  branch: master
media_folder: "static/images"
collections:
  - name: "site_pages"
    label: "Site Pages"
    folder: "content"
    create: true
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}